name: shop
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=shop
    ports:
      - 3306:3306
